FROM oven/bun:slim

# Add python and ffmpeg for youtube-dl
RUN apt-get update && \
  apt-get install -y python3 ffmpeg && \
  # Clean up apt cache
  apt-get clean && \
  # Remove unnecessary files
  rm -rf /var/lib/apt/lists/*

ENV NODE_ENV=production

# Install deps for production
WORKDIR /app
COPY package.json bun.lock ./
RUN bun install --prod --frozen-lockfile

# Copy the source files
COPY src/ ./

# Start the app
CMD ["bun", "start"]