# Each of the services below runs a different bot, you may not want
# to run all of them at the same time.

services:
  # Run the dev bot with hot reloading of local files
  dev:
    container_name: mp4ify_dev
    image: mp4ify_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.dev
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    devices:
      - /dev/dri:/dev/dri
    working_dir: /app
    user: '${UID:-1000}:${GID:-1000}'

  # Run the prod bot using a pre-built image (TODO)
  prod:
    container_name: mp4ify
    image: mp4ify
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env.prod
    volumes:
      - ./.prod-video-cache:/app/.video-cache
    devices:
      - /dev/dri:/dev/dri
    working_dir: /app
    user: '${UID:-1000}:${GID:-1000}'
    restart: unless-stopped

volumes:
  videos:
