FROM oven/bun

# Install yt-dlp dependencies
RUN apt-get update && \
  apt-get install -y python3 ffmpeg curl && \
  # Install yt-dlp
  curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp && \
  chmod a+rx /usr/local/bin/yt-dlp && \
  # Clean up unnecessary files
  apt-get remove -y curl && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

RUN mkdir /storage && chmod 777 /storage

ENV NODE_ENV=development

# Since the entire working dir will be mounted, we can't install deps here
WORKDIR /app

# Make sure deps are installed & start the app in watch mode
CMD ["sh", "-c", "bun install && bun dev"]