FROM oven/bun

# Add python and ffmpeg for youtube-dl
RUN apt-get update && \
  apt-get install -y python3 ffmpeg && \
  # Clean up apt cache
  apt-get clean && \
  # Remove unnecessary files
  rm -rf /var/lib/apt/lists/*

ENV NODE_ENV=development

# Since the entire working dir will be mounted, we can't install deps here
WORKDIR /app

# Make sure deps are installed & start the app in watch mode
CMD ["sh", "-c", "bun install && bun dev"]